### ISSUE TITLE
March 3rd 2015 Twitter Chat (5PM PST, 8PM EST) - Barriers to Learning at Work

### ISSUE THREAD

**Issue by zspencer** [zincmade/apprenticeship.community-wip#1]
Topic is still up in the air!

Contenders:

1. Knowing when to earn vs. when to learn (i.e, how do you decide when it's time to learn something new instead of pushing forward with what you know?
2. Barriers to Learning at Work

**Comment by JayNewlin** [comment]
I'll +1 both topics. They're both big topics, and adding more might make it difficult to keep up with the threads.

**Comment by zspencer** [comment]
I'm gonna go with barriers to learning at work for this one! We'll do another topic next week on earn vs learn

**Comment by zspencer** [comment]
Final tweet summarizing everything: https://twitter.com/pprenticeship/status/572963519538200576
