### ISSUE TITLE
AMA with Sarah Mei

### ISSUE THREAD

**Issue by zspencer** [zincmade/apprenticeship.community-wip#2]
We've got @sarahmei interested in spending an hour talking about her experiences starting RailsBridge, working at Pivotal, and running her own consultancy!

**Comment by zspencer** [comment]
/ccing @kmanion as she's the one doing all the planning for this.

**Comment by zspencer** [comment]
@sarahmei would Tuesday at 5PM PST/8PM EST work for you for an hour?

**Comment by sarahmei** [comment]
Can't do that time exactly; I could do earlier on Tuesday at 4, or 5pm Weds?

**Comment by zspencer** [comment]
Hmm, I hate to double-book at the same time #CodeNewbie's twitter chat is going on. 4PM PST/7PM EST should be OK.

**Comment by kmanion** [comment]
:+1:

**Comment by sarahmei** [comment]
Ok, got it on my calendar for Tuesday 3/10 at 4pm PT. \o/

**Comment by zspencer** [comment]
Woo! I just announced:
https://twitter.com/pprenticeship/status/573961078637355008
<https://twitter.com/pprenticeship/status/573961078637355008>


Would love to spread this far and wide!
